### ISSUE TITLE
[Improvement] Remaining cards counter in PlayMode

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#1]
When playing a game in Play Mode, there is no way to know how many cards are left in your deck. We should add something to solve this, either a simple label or something more fancy like an actual stack of cards.

**Comment by Chibi1234** [comment]
Just speculating but I would guess the amount of cards in your hand are counted someway and are tracked. So if we could add a label that retrieves the amount of cards in your hand (graveyard,play or discard) and minus that with 30 we would get a card counter. Wouldn't we? Also we need a way to see which cards are burned because I had no idea I accidentally milled my Malygos in my Malygos Rogue -.-

**Comment by webadict** [comment]
Adding a log like that is in the code. Turning on the logging should let you see what you burned. Also, adding the deck counter isn't quite the hard part, Chibi. It's putting it into the interface that's hard. Something simple like 'Cards Remaining: 22' involves a few interface changes. I'm looking into it, though, because I, too, would like to see the number of cards.

**Comment by webadict** [comment]
I added a Card Counter for you. It's not anything spectacular, but it does what it's supposed to do.
