### ISSUE TITLE
[Explosive Trap] + [Freezing Trap] interaction

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#100]
Freezing Trap will still trigger even if an Explosive Trap is queued to trigger first and kill the attacking minion. The fatal damage is ignored and the minion is returned to the owner's hand. What should happen is that Freezing does not trigger at all when the minion is dead.

I looked into this, but was unable to find a quick fix. I think it is related to the trigger changes, where we now first collect all triggers which are supposed to fire, instead of firing triggers instantly. This is correct for almost all triggers, but I suppose secrets are a special case in that regard.

On that note, I discovered the following code in TriggerManager class:

```
// In order to stop premature expiration, check
			// for a oneTurnOnly tag and that it isn't delayed.
			if (event.getEventType() == GameEventType.TURN_END &&
					trigger instanceof SpellTrigger) {
				SpellTrigger spellTrigger = (SpellTrigger) trigger;
				if(spellTrigger.oneTurnOnly() && !spellTrigger.isDelayed() &&
						!spellTrigger.interestedIn(event.getEventType())) {
					spellTrigger.expire();
				}
				spellTrigger.delayTimeDown();
			}
```

@webadict Could you explain what this code is doing? I checked all cards and could not find any card which actually sets the turnDelay. I would really like to remove this piece of code if it is not used right now.

**Comment by webadict** [comment]
No cards use turn delay yet, but if it's ever need (say an effect happens
at the end of your next turn) then I wanted a way to access it. Currently,
we have no way to reach future turns with effects, and this was a way to do
that.

Turn delay should default to zero if not set, and it shouldn't affect
anything. Promise!

What I DID fix was Lock and Load. Lock and Load would fire once and expire
itself with the old code, which has now been fixed. Also, if a oneTurn
effect happened on the opponent's turn, there needed to be a way to delay
the expiration, hence the turnDelay, which counts all player's turns.

Also, what you want to quickly fix freezing trap with is the
isDeadCondition. Since it takes fatal damage, it should stop it from
returning to hand. Although, the way I've seen the two interact, the minion
returns to hand, but maintains its destroyed attribute, but this was a long
time ago, so I don't know if that's still true.

However you are sort of right about the trigger changes, but not the most
recent fix. This was from the fix a long time ago, where the effects were
all queued to fix Hobgoblin. Some triggers should stop firing due to
destroyed or owner changes, but do not. I can explain why, but it's a bit
complicated. This is something I've been thinking about for a while, and
haven't come up with a better solution.

**Comment by demilich1** [comment]
Okay, so basically the turn delay is for future use? In this case I don't like it too much to be honest, as the code in the TriggerManager is not very nice in my opinion. It makes reasoning about triggers quite complicated, especially for people new to the code.

IsDeadCondition does not help for the Freezing Trap/Explosive Trap interaction issue, since the minion is not dead when both traps are checked, I already tried that. We may need a special case for secrets in the TriggerManager, because for regular minion triggers the queuing up is correct in my opinion.

**Comment by webadict** [comment]
Ah, right. Well, to follow the way Hearthstone works would make sense.
There are two conditions for trigger effects: queue condition and trigger
condition (this is also true for deathrattles, but they do not linger like
triggers, so they work as intended.) If the queue condition is true, then
it enters the queue and if the trigger condition is true it fires.

For us, these would be the trigger's condition and the spell's condition.
However, we only check the spell condition after entering the "will fire"
queue. So, we either need two conditions for triggers (one for queueing,
one for firing) or we need to check the spell's condition before firing.

Also yeah, that makes sense. It would work better if they were all the
same, which is doable, but I was a bit lazy. I can standardize it if you
want, or you can remove it. It just seems like a good idea for triggers.

**Comment by demilich1** [comment]
Having two separate triggers (one queue, one trigger) would work, that is a good suggestion. However, I am still wondering if there is a simpler solution. It kind of irks me to implement such a mechanic for just one special card interaction. Because in almost all other cases having just one condition is fine. Also we recently had an issue where the Knife Juggler would continue to hit dead minions. So maybe we just need a better way to cancel effects when entities are dead? I think I am going to think about that a bit longer before implementing anything.

**Comment by webadict** [comment]
Well, that's not right though. Some effects DO hit destroyed units, and
some effects do occur when a minion looks like it's destroyed. Like Brann +
Stampeding Kodo can hit the same minion twice. We don't want to avoid
targetting dead minions unless they should be avoided, like Knife Juggler.

**Comment by demilich1** [comment]
Yeah of course, most of the time we want to hit dead minions. I was thinking more about something like a flag "worksOnDeadMinions" which would be true by default and i.e. Knife Juggler or Freezing Trap could set this to "false". However, it is basically the same as the IsDeadCondition and would not solve the underlying problem (except we also check that flag again when firing)

**Comment by webadict** [comment]
Well, Knife Juggler isn't an issue anymore anyhow. Switching the spell it cast was the main issue, and it works perfectly at the moment.

Honestly, I think I can check to see if it can fire a better way. I don't like having additional one-off cases like this. There should be reasons for all of this, and in this case, it does have one. Spells have conditions as well, and we can check them to stop them from firing secrets. But maybe most triggers SHOULDN'T target dead targets anyhow. I'm trying to think of a trigger that would apply, but none stands out. But even then, this is a trigger firing queue issue. This is a bigger bug than just Freezing Trap, and you can see this with more cards. But, we have to be careful not to remove things like on-damage triggers, which can apply so long as the minion is not pending destruction (Acolyte can be triggered multiple times below 0 Health, like multiple explosive sheep activating in the same death resolution step.)

**Comment by webadict** [comment]
Oooo, also noteworthy! [Repentance targets dead minions!](https://www.reddit.com/r/hearthstone/comments/4asjis/til_repentance_revives_sniped_minions/) So, that means triggers should target dead minions!

I'm still under the impression that Freezing Trap's spell has a condition to stop it from firing on dead minions.

**Comment by webadict** [comment]
Alright, I've been thinking about it. I think your method probably works best for now, and it can be changed in the future. I'll try to implement it now, and I'll standardize the Trigger Manager.

I think in the future, there should be a queue condition and firing condition added to triggers and deathrattles, since this will actually fix a couple of other smaller bugs.

**Comment by webadict** [comment]
Trigger Manager standardized for each trigger type.

**Comment by demilich1** [comment]
Have to reopen this, unfortunately the test still fails which means this is not yet working as intented

**Comment by webadict** [comment]
Ah, yeah, I forgot the update to IsDeadCondition. Whoops!
