### ISSUE TITLE
[Boom Bot] Hits dead minions

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#105]
Another bug report I received via email:

*Boom Bots are targeting dead minions. For example, if you control a 1/1 Imp and Flamestrike a board of 7 Boom Bots, several of the Boom Bots will probably hit the 1/1 Imp.*

We can probably fix this by also changing the Boom Bot spell to 'MissilesSpell' as we did with Knife Juggler - however, somehow this feels like a work-around to me instead of a proper fix. We are just exploiting that MissilesSpell does not target dead minions. Why don't we add the same property to the vanilla DamageSpell (or all spells that need it actually)?

**Comment by webadict** [comment]
Yeah. I've fixed every instance of this in my next PR. No prob.

**Comment by webadict** [comment]
And as for why NOT to add this to DamageSpell, things like Brann into Elven
Archer on a 1/1 Acolyte of Pain would fail, which is absolutely not what we
want.

**Comment by demilich1** [comment]
Yeah, should have made clear that I of course meant something like an optional attribute
`"canHitDeadStuff" : false (default would be true)`

**Comment by webadict** [comment]
That's not really needed for two reasons:

1. MissilesSpell does exactly what we need right now. The only
non-dead-targetable damage sources are all random. Which leads to the next
point:

2. You already have that tag. It's just called randomTarget instead. Any
randomly targeted ability should never hit a dead target. The only one I'm
iffy on here is healing, but random healing sources are rare. But my guess
is it wouldn't.

However... this only applies to HP <= 0. This does not count the Destroyed
attribute. The reason this is important is because Brann + Stampeding Kodo
CAN destroy the same target twice.

I've fixed every source of random damage as of the last PR. There's only
one minor issue I fix in my next PR, but this isn't really that big. The
only might be random buffs, but too few exist to test this out properly.
