### ISSUE TITLE
Test uncommon card interactions 

### ISSUE THREAD

**Issue by mayuso** [demilich1/metastone#110]
I just found this post, and thought about posting here about this interaction, I am not sure if things like this have been already taken into account in MetaStone, so sorry if you already did:

[Reddit post](https://www.reddit.com/r/hearthstone/comments/4day6j/if_you_attack_a_hunter_with_misdirect_and/)

If this is tested and implemented, feel free to close this issue, if not, I'll try to test this asap, seems interesting.

**Comment by webadict** [comment]
:P This actually should work. Give it a test!

**Comment by webadict** [comment]
Well look at that. It doesn't! But not because of the interaction. It's because Explosive Trap doesn't queue at the same time Misdirection would.

**Comment by webadict** [comment]
I remember this now... I tried to fix this a while ago, but there's currently an issue with why it doesn't work:

When attacks are processed at first, you have a Target Acquisition Event. Basically, you selected a Physical Attack Target. This is where Misdirection and the Ogre subtype calculate who they're hitting (Same with Noble Sacrifice.) When these targets are changed, whatever previous attack target was selected is forgotten. It never procs the traps or any thing else.

Notice that Explosive Trap was never mentioned here.

The issue here is that Misdirection is supposed to be on the same Trigger as Explosive Trap, but it's programmed on the Trigger before it. BUT, simply switching this doesn't fix the issue, since it would still forget what's being attacked one way or the other.

There's not really an easy way to fix this. The necessary condition is programmed in (You could create a card that summons a minion when it attacks, so that a bunch of Knife Jugglers might kill the minions target, and it would be able to attack again, which would summon another minion, too.) The issue is the Trigger and Event layering, as well as the handling.

I might have to do some Hearthstone sciencing in order to figure out a few things. There's not as much information currently out there about what I'd like to know.

**Comment by webadict** [comment]
I think I can fix this, but it involves testing the card order in Hearthstone: If I play Snake Trap, Misdirection, and Explosive, in what order does that go off? My guess is that it goes by attack order, so the order goes

Snake Trap (Do not queue, target not attacking a minion.)
Misdirection (Queue, target is attacking hero.)
Explosive Trap (Queue, target is attacking hero.)

So the trigger queue now holds Misdirection and Explosive. So, when Misdirection redirects the attack to, say, another owned minion, it rechecks for triggers. Misdirection has already fired and is therefore expired and cannot be checked, but

Snake Trap (Queue, target is attacking a minion.)
Explosive Trap (Do not queue, target is attacking a minion.) <-- Odd, but likely what happens internally. Even if it said Queue, it wouldn't be able to trigger, since it will expire earlier in the queue.

After that, the Queue is now Explosive Trap -> Snake Trap in that order. So, even though Snake Trap was played first, it will fire after all of the other traps. That's test one.

But if this is true, then it worries me about the Ogre subclass. Can Ogres proc multiple times in an attack? If there's a board full of Mogors, can any of them affect a minion more than once? Or do triggers only go off once per event call? My guess is the second, but how can I achieve the same results?

**Comment by webadict** [comment]
Wait, why was this closed? This was never solved.
