### ISSUE TITLE
Missing tag "collectible" from some of the .json card files

### ISSUE THREAD

**Issue by albertotonda** [demilich1/metastone#111]
While looking at the .json files describing the cards in metastone, I noticed that the tag "collectible" (true/false), present in most of the entries, is missing from a significant number of Mage and Neutral cards in the Classic set.

**Comment by webadict** [comment]
Hey Alberto!

This is correct. Right now, the default collectible status is `true`. This is mostly because a long time ago when these cards were first made, the collectible tag was only given to those that weren't collectible. To be fair, this tag isn't needed, but rather kept in order to standardize cards (So if you take one and edit it, it won't matter!)

So, basically, it's fairly low on our list to fix at the moment, but it might be addressed eventually.
