### ISSUE TITLE
[Blizzard] Freezing spawned minions

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#118]
Received via email:

_When minions such as Imp Gang Boss and Dragon Egg are damaged by Blizzard, the minions they spawn should end up frozen._

Can anyone confirm this? It seems really strange to me, as it would mean they get hit by the freeze effect but not by the damage.

**Comment by webadict** [comment]
Confirmed.

**Comment by mayuso** [comment]
Taken from the [Hearthstone Gamepedia](http://hearthstone.gamepedia.com/Blizzard)

> Blizzard deals its area of effect damage first, and then applies its Freeze effect as a separate event. This means that an enemy minion resulting from an effect triggered by the damage will be Frozen, but not damaged itself. This has been confirmed as working correctly.

**Comment by webadict** [comment]
Also, easy solution to this one: Move the targeting into each MetaSpell slot. Since the damage portion happens first, you can have all enemy minions take damage, and then freeze all enemy minions. This shouldn't freeze minions from deathrattles, as they die after the freeze effect happens, so it should work fine.

I will PR the fix, but I'm still commiting fixes a small amount at a time, and I'm waiting for these ones first.

**Comment by demilich1** [comment]
Good call, moving the targeting into the sub -pells of the MetaSpell worked like a charm
