### ISSUE TITLE
[Bear Trap] Wrong interaction with Freezing Trap

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#151]
Bear Trap is activated by a lone attacker that was returned to hand by a Freezing Trap. From http://hearthstone.gamepedia.com/Bear_Trap:

_"Bear Trap will not activate if the attack does not complete, e.g. because the attacker died or was returned to hand before it could hit its target, such as by Freezing Trap."_

**Comment by webadict** [comment]
I think moving the secret to a different Trigger would probably fix this, but I don't think we have an After Attack Trigger. Right now it summons as the Hero is attacked, which is incorrect, so this fixes multiple issues. I'll get something up here soon.

**Comment by webadict** [comment]
Hmm, I'm removing the Secret Layer applying first, since it makes no sense to do that. The reason being that some events should go off even if the Attacker dies due to a trap (Let's say, Explosive Trap killing a 2 Health minion with Blessing of Wisdom.)

The ones that shouldn't (Like, Magnataur Alpha), can be moved to the AfterAttackEvent.

**Comment by webadict** [comment]
This should work due to the fix to triggers a bit ago. Now, if you play Blessing of Wisdom on an enemy minion, then play Freezing Trap, the BoW should proc first, then return the minion to hand. If reversed, the BoW shouldn't proc at all, since the minion carrying the effect (And by extension, the effect itself) has been removed from the board.
