### ISSUE TITLE
[Bug] Deathrattle effects when multiple minions die

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#16]
I just received a bug report from a user:

"Dark Cultist's deathrattle will still buff a minion even when those minions should have died at the same time. For example, if I Flamestrike a board with a Dark Cultist and a Dark Iron Dwarf, the Dark Iron Dwarf will survive."

I was able to verify this. When the Dark Cultist was summoned first, its Deathrattle will buff another minion. I wrote a unit test for this problem, which fails at the moment.

While this is certainly possible to fix, we should be very careful with that. My first naive "fix" broke a lot of other stuff.

**Comment by webadict** [comment]
It should be worth noting that deathrattles happen in both the order they were played AND the order in which they are killed on minions that would be alive after they died, but not necessarily alive when it happens.

An example for this would be a board with the following played order: Explosive Sheep, Explosive Sheep, Unstable Ghoul, Chillwind Yeti, Dark, Cultist. By killing one of the Explosive Sheeps, you trigger the next Explosive Sheep, which kills both Unstable Ghoul and Dark Cultist. At this point, the only remaining living minion is Chillwind Yeti, so Unstable Ghoul's deathrattle DOES NOT kill Chillwind Yeti, because Dark Cultist's deathrattle will grant the extra life needed to save the Chillwind.

**Comment by webadict** [comment]
One test case you might use to test Deathrattles following the correct procedure is this: 
Player 1 has a Sylvannas played before all Player 2's minions. Player 2 has the following minions played, first to last: Explosive Sheep, Explosive Sheep, Haunted Creeper, Haunted Creeper, a buffed 2/3 Haunted Creeper, another buffed 2/3 Haunted Creeper, and an injured 5/3 Sylvannas.

Death Phase #1: An Explosive Sheep takes 1 damage and is destroyed. Explosive Sheep's deathrattle deals 2 damage to all other minions.
Death Phase #2: Explosive Sheep #2 and both unbuffed Haunted Creepers are destroyed. All remaining minions take 2 more damage, and then 4 1/1 Spectral Spiders are summoned.
Death Phase #3: Both buffed Haunted Creepers and Player 2's Sylvannas are destroyed. 3 1/1 Spectral Spiders are summoned, and then Sylvannas' deathrattle attempts to steal Player 1's 5/1 Sylvannas, destroying it, as there is no more space on Player 2's board.
Death Phase #4: Player 1's Sylvannas steals a 1/1 Spectral Spider.

Deathrattles are triggered in Phases, so that all minions that were destroyed at the beginning of the Death Phase should be dead and their deathrattles triggered by the end of the Death Phase. Then, all minions are checked again to see if they're destroyed, and all of those minions are triggered during the next Death Phase.

Currently, Metastone checks each individual minion for destroyed checks, removes them from the board, and then triggers their deathrattle. This circles multiple times until no remaining minions are destroyed.

The fix to this is... rather complicated and annoying. Rewriting the checkForDeadEntities method involves setting up Death Phases, and applying the deathrattles appropriately before rechecking entities for death.

I'll try some stuff this weekend maybe.

**Comment by webadict** [comment]
Just did a quick rewrite of death checking. I know, I'm pretty awesome. I'll add it to the next PR.

**Comment by webadict** [comment]
This should be fixed as of now.
