### ISSUE TITLE
[Steward of Darkshire] + Buff auras

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#170]
Another bug report received via email:

_If there's a Murloc Warleader on board, Steward of Darkshire shouldn't give any summoned Murlocs with 1 health Divine Shield. There are several notes detailing this timing at [http://hearthstone.gamepedia.com/Steward_of_Darkshire](http://hearthstone.gamepedia.com/Steward_of_Darkshire)_

And a follow-up:

_Regarding the Steward of Darkshire bug: I noticed the bug only occurs when a 1 health minion is summoned through a battlecry. For example, if you play a Bilefin Tidehunter while controlling a Stormwind Champion and a Steward of Darkshire, Metastone will correctly ignore the Bilefin, but will then grant the summoned Ooze Divine Shield. The same thing occurs if you substitute a Murloc Warleader for the Stormwind Champion and then play a Murloc Tidehunter: Metastone will correctly ignore the Tidehunter, but will then grant the summoned Murloc Scout Divine Shield._

**Comment by webadict** [comment]
My guess is that this has to do with when auras are updated. Murloc Tidehunter is actually a funny example, since auras are updated at the end of a minion summon resolution, which happens after the battlecry phase, but since another minion is summoned during its battlecry phase, the aura updates on all minions, including Murloc Tidehunter itself, which hasn't finished resolving its own summon, but is considered in play.

**Comment by webadict** [comment]
I'll test out moving the aura updating to sooner rather than later.
