### ISSUE TITLE
[Tuskarr Totemic]

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#182]
Received via email:

_[Tuskarr Totemic] sometimes summons [Vitality Totem] in Standard format, which should not happen as [Vitality Totem] belongs to the Goblins vs Gnomes set._

I cannot start MetaStone right now to verify this, but looking through the .json files everything seems to be correct. Can anyone confirm this?

**Comment by webadict** [comment]
I have never seen this happen, but I'll do a code check to see if it's
possible. I don't think it is, seeing as how the vitality totem shouldn't
be added as a choice, but maybe the uncollectible tag adds it?

**Comment by webadict** [comment]
Well, look at that. The uncollectible tag lets it skip past it due to the way it queries.

Easiest fix looks to be to change CardCatalogue from

	public static CardCollection query(Predicate<Card> filter) {
		CardCollection result = new CardCollection();
		for (Card card : cards) {
			if (filter.test(card)) {
				result.add(card);
			}
		}
		return result;
	}

to something more like:

	public static CardCollection query(DeckFormat deckFormat, Predicate<Card> filter) {
		CardCollection result = new CardCollection();
		for (Card card : cards) {
			if (!deckFormat.inSet(card)) {
				continue;
			}
			if (filter.test(card)) {
				result.add(card);
			}
		}
		return result;
	}

Any queries will need to be updated (SummonRandomFilteredMinionSpell for sure.) And this MIGHT effect RandomDeck, which I haven't bothered touching due to how it grabs its random cards (Did you know that it still doesn't care about Standard/Wild formats? That's because I had to drag the DeckFormat through about 5 unrelated classes in order to make it care, which didn't seem worth it and made a bit of a mess.)
