### ISSUE TITLE
[Release] 1.2.0 - One Night in Karazhan

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#215]
I just bundled together the first internal test version of 1.2.0. Head over to the release section if you want to try it (of course, you can also compile it yourself).

Once again, all cards were implemented by @webadict. Thanks a lot!

Please do report any bugs you may find.

**Comment by cydlord** [comment]
Hi, I'm getting an error in [spell_mindgames.json]. Updated the program from 1.1.1, using the installer. Also tested it on a separate folder, but same result. It's still playable, but none of the kharazan cards are showing.

**Comment by demilich1** [comment]
Yes, that bug is known and should be fixed with the next version. As a work-around, you can delete your Documents/metastone folder. The next time you start MetaStone, you should see all Karazhan cards

**Comment by webadict** [comment]
I pushed some more updates. I think it calls for RC2. They're actually some really nice functionality updates, as well as making Jaraxxus work as intended (Redirects the secrets to him.) There's some additional fixes that probably need to be added to go along with that (Knife Juggler should NOT throw knifes, since his summoning technically never resolves), but those are relatively easy as long as these work.

And I removed that dreaded "resolvedLate" tag. I never want to see it again!

**Comment by demilich1** [comment]
Just uploaded 1.2.0RC2, feel free to test it!

**Comment by demilich1** [comment]
I just bundled the release 1.2.0RC3; I would like to release this build officially as 1.2.0 when no major issues arise

**Comment by webadict** [comment]
I've been playing with it for a while. I think it's fine, but that's just my opinion.

**Comment by webadict** [comment]
Also, I'm only adding stuff because that's what I do. If you need to release it, I don't mind the updates being delayed to the next version.

**Comment by demilich1** [comment]
I just published MetaStone 1.2.0 on http://www.demilich.net/metastone

That means the development of 1.2.1 has just begun ;)
