### ISSUE TITLE
[Documentation] Create basic documentation

### ISSUE THREAD

**Issue by mayuso** [demilich1/metastone#22]
I found this project searching github repositories and i am really interested in helping, i also love HearthStone.
I tried to undestand the code but its almost imposible without some kind of documentation.

Im not asking for full detail documentation for every class and method, but at least some basic flowcharts (or any similar idea) would help people like me get more involved in the project. And when more people get involved, getting a fully documented project is easier, because you simply have more people willing to do it.

(Sorry for any english mistakes)

**Comment by webadict** [comment]
Hey Mayuso!

I absolutely agree with you. I suppose I could start adding some javadocs to classes as a good start, and I might have to start adding some when I make a new class, just for good practice.

I guess I should start off with asking about what you mean by a basic flowchart. Do you mean something similar to a run-down of how things happen from one end to the other? (Like, as an example, what happens when a card is played? Or how does a spell work? Because I only somewhat understand those myself, but I can give you a very basic flowchart of how a few things work here.)

Honestly, it is a little tough to start working on this project. I know when I started, I could really only figure out what the cards did. I could probably write up some documentation for how the cards should be written, as well as re-formatting the current cards into streamlined fit.

Also, your English is just fine. The only thing you're missing is apostrophes, but this is the internet, so no one cares about those.

**Comment by mayuso** [comment]
Thank you :)

I actually meant a graphical visualization of what classes call to what classes, not sure if that makes sense to you. (Its basically what software like doxygen does).

But your idea is also really good, and i think even better than mine, a simple step-by-step description of the program would help a lot (Without really needing much detail, good code doesn´t need much detail).

**Comment by mayuso** [comment]
Ok, i will just try to learn by using it. I might end up doing the charts myself if i manage to understand the program :) I hope so.
