### ISSUE TITLE
League Of Explorers!

### ISSUE THREAD

**Issue by Chibi1234** [demilich1/metastone#24]
WE NEED LOE!!!!!!! *Raises pitchforks!* We shall burn demilich if he does not answer to our pleads! 

bawhahawbabwhabwha! 

LoE! LoE! LoE! LoE! bwahbwhabhwhabwbhawbahwb!

*Gathers a stack of wooden sticks and light em on fire!*

We want LoE!

**Comment by Chibi1234** [comment]
And also a quickie, how do i make a card that makes ur hero immune? When i try to edit Mal'Ganis my brain explodes,

**Comment by webadict** [comment]
Hey Chibi!

LoE has been about 90% implemented, but is still undergoing some tests to
make sure everything is compatible. The fast release cycle made this a bit
of a rush, but it still takes a bit of time to release (plus the Discover
mechanic is a whole new can of worms.)

If you would like most of the cards immediately, you will have to compile
my fork of the project.

When all the cards are implemented, I'll let you know.

As for the Immune question, I would prefer if you created a separate Issue
for that, so that this Issue can focus mainly on LoE.

Thanks!

**Comment by Chibi1234** [comment]
O-O that... was fast... thx... ehm... 

''If you would like most of the cards immediately, you will have to compile my fork of the project.''
How do that? :confused:

**Comment by webadict** [comment]
Remaining LoE cards to implement:
-Djinni of Zephyrs
-Summoning Stone
-Jungle Moonkin
-Animated Armor
-Anyfin Can Happen
-Tunnel Trogg
-Cursed Blade

**Comment by mayuso** [comment]
I´d love to help on this, i just can´t, yet.

**Comment by Chibi1234** [comment]
Are the cards expected to be done and available for play around tomorrow or today? IM JUST REALLY HYPED :D

**Comment by webadict** [comment]
Not likely, Chibi. They'll probably be more towards the end of the week.

**Comment by Chibi1234** [comment]
Awwwwww T3T

**Comment by webadict** [comment]
All cards are added. Some minor background issues still exist and will be addressed as soon as possible.

**Comment by Chibi1234** [comment]
Yayyyyyyyyyyyyy!

**Comment by demilich1** [comment]
Merged webadict's branch, thus all League of Explorer cards are now in master
