### ISSUE TITLE
Avenge doesn't trigger when you have exactly 2 minions

### ISSUE THREAD

**Issue by Lykrast** [demilich1/metastone#247]
After some testing to trying to reproduce it in Sandbox, Avenge doesn't trigger if you only have 2 minions on the board when it triggers.

Looking at the card code, it seems to be a "greater" instead of "greater than" issue on the minion count condition, as chaging them to "GREATER_OR_EQUAL" fixed the issue for me.

**Comment by demilich1** [comment]
I fixed this by setting the value to 0 instead of 1 (of course, GREATER_OR_EQUAL would have also worked). This may be related to the removal of the SECRET layer, I am not sure actually. It seems that the MinionDeathTrigger now fires after the minion has been removed from the board; therefor the condition is now slightly changed. When a minion dies and has been removed from the board and there is still at least one minion left, then fire Avenge
