### ISSUE TITLE
Brann+King's Elekk

### ISSUE THREAD

**Issue by DominusMaximus** [demilich1/metastone#278]
There's something up with the interaction between Brann and King's Elekk. In sandbox mode I set up two identical decks containing 20 Wisp and 20 Leper Gnome. I put Brann into play and started playing several King's Elekk. For some reason I would draw Wisp off of King's Elekk, which shouldn't be possible since it's 0 mana. 

I did another test with a deck containing the same 20 Wisps and Gnomes, and the Brann+Elekk deck containing 20 Wisp and 20 Ironfur Grizzly. Since the Grizzly is 3 mana, it should always be drawn whenever it appears within the Joust animation, however I would still only receive Wisps. When Brann is involved the Joust animations are a bit of a blur, so I couldn't tell which 2 cards were being matched up, though I could at least make out the Grizzly.

**Comment by webadict** [comment]
Looks like an issue with King's Elekk. The effect isn't activating at all, win or lose, for me... Weird. I'll check it out.

**Comment by webadict** [comment]
Hah! Weird. So, the real issue is Sandbox Mode. Apparently, when you modify the deck, it creates a few issues. The first and most significant issue is that your deck... kinda isn't updated when you change it all out like that. The second and most disastrous issue is that any cards removed from your deck stop existing... Including spell triggers attached to them. Typically, this isn't an issue! There was only ever one minion with a deck trigger, and that was Prince Malchezaar, but due to the way it originally worked, it wasn't ever applied in Sandbox mode... But this was fixed. And so, it and Patches the Pirate, when removed from the deck in Sandbox mode, crashed the simulator.

So, that's another bug squared away.

**Comment by DominusMaximus** [comment]
Oh ok. What first led me to that sandbox test was playing that combo in Play Mode and losing both Jousts. Something didn't seem right, but I wasn't sure because of the quick animations. Glad to hear it's working correctly in Play Mode.

**Comment by webadict** [comment]
Spacing out animations might be a good idea eventually, but it's fairly difficult to space out at the moment. I'll see if I can help out with that.
