### ISSUE TITLE
[Bug] Defender of Argus interaction leads to crash

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#29]
There is a crash playing Defender of Argus when you have Brann Bronzebeard on your side of your board, more than 3 minions and your opponent has the Paladin secret 'Sacred Trial' active

**Comment by webadict** [comment]
It seems to be any minion with an adjacent minion targeted battlecry. This includes Defender of Argus, Sunfury Protector, and Ancient Mage

My guess is that there's something that resolves deaths before the battlecry finishes, so the minion doesn't have any adjacent minions at the start of the second battlecry. Haven't really checked just yet, but that's my guess.

**Comment by webadict** [comment]
Huzzay! I'm correct, and it's now fixed!

**Comment by webadict** [comment]
On a side note, this does mean we should probably do a proper rewrite of summoning procedure as well while deathrattles are being looked at.

The only card that should have a late resolution is Redemption, since that's the only card that does something like that. Battlecries should all go off BEFORE the minion is summoned but AFTER the minion enters play. There's a whole bunch of oddities that can be fixed by doing something like this, and death resolution can be proper as well.

... Eh, it'll go on the to-do list.

**Comment by webadict** [comment]
And yes, you shouldn't resolve the deaths until after the battlecry happens. So, if a Fire Elemental's battlecry targets an Acolyte of Pain with Brann Bronzebeard on the field, it should target twice before deaths are processed, since the Battlecry Phase is simply played an additional time.

**Comment by demilich1** [comment]
Confirmed that Sacred Trial crash is gone
