### ISSUE TITLE
Unable to execute file

### ISSUE THREAD

**Issue by BettyJJ** [demilich1/metastone#296]
Just downloaded and installed the latest release metastone-1.2.0_installer.zip. After installation clicked 'launch'. And this showed up:

> Unable to execute file:
> d:>Metastone\Metastone.exe
> CreateProcess failed; code 216.
> %1 of this version is incompatible with the Windows version you are running.

I'm running on Windows 10, 32-bit.

**Comment by mayuso** [comment]
I can't really tell for sure (I am not one of the core mantainers), but I would bet it's because you have a 32 bit Windows.

Usually, when creating `.exe` files, you need to decide if you create it for 64 bits or 32 bits (At least that's how it works in Visual Studio for C++, so I am going to make the inexperienced assumption that it also happens in metastone).

**Comment by BettyJJ** [comment]
@mayuso Thanks for the reply, but I'm downloading the installer from this release page [https://github.com/demilich1/metastone/releases], on the page nothing is said about 32-bit or 64-bit.

**Comment by demilich1** [comment]
@BettyJJ  Sorry that you are having issues with the Installer. Indeed the installer version is only working for 64 bit Windows (and I will make sure to add this to future releases).

But you are not out of luck: You can still use the .zip or .tar version, which includes a runnable .jar. This will work on any OS which has a Java VM implementation. So as long as you installed an up-to-date JRE 8, you should be able to start MetaStone by downloaded the metastone-1.2.0.zip and run metastone-1.2.0\bin\metastone.bat

**Comment by BettyJJ** [comment]
@demilich1 The .jar way works fine. Thank you!
