### ISSUE TITLE
Release 0.9.9 ready for testing

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#32]
Hi all,

I just uploaded binary versions of the 0.9.9 release to github. First, it will be available on github only to perform some more testing. After some days I will publish it on my website and enable the update notification in the program.

So, everybody is invited to download the release and test it. Please do report all bugs you find.

Special thanks to webadict for implementing all of the LoE cards!

**Comment by mayuso** [comment]
I will download and start testing as soon as i get home.

Amazing Job, specially webadict and demilich1. Thank you!

**Comment by cydlord** [comment]
Darnassus Aspirant battlecry does not add 1 empty mana crystal. Its deathrattle is working as intended.

**Comment by SirFatCat** [comment]
I'll test it, too.

**Comment by webadict** [comment]
I won't be home for some time, but same.

**Comment by webadict** [comment]
Uhh... wtf is up with Grove Tender? And seriously wtf is wrong with Darnassus?!?

Basically, Darnassus' battlecry goes off just fine, but then it sets up the deathrattle... And seems to actually proc the deathrattle as well, since removing the deathrattle actually allows the battlecry to go off accurately.

Turns out, (TOSHLEY CONFIRMS THIS!) that Battlecry minions, sorta, proc their deathrattle when they proc their battlecry. So, anything that has a Battlecry and a Deathrattle has this issue.

... Well, crap, I think I know why, too... And I'm pretty sure it's my fault.

Grove Tender doesn't give the correct amount of mana though. That's a separate issue though.

**Comment by webadict** [comment]
All bugs except for Deathrattles and Battlecry activations that have been identified should be fixed now.

**Comment by SirFatCat** [comment]
Has the Deathrattle/Battlecry stuff been fixed? It seems so from what I can see, but I'm just wondering to make sure. If so, I'd agree that 0.9.9 should be released soon. :)

**Comment by webadict** [comment]
I haven't pushed the changes, but it's fixed on mine for now. I was fixing a few other things and running simulation tests to make sure everything worked.

**Comment by webadict** [comment]
There seems to be an issue with Game State Value trying to determine the score of which minion to transform too, since the minion gets lost... Hmm...

**Comment by webadict** [comment]
Alright, newest PR should now fix deathrattle issues, along with all of the identified bugs. Battlecries still need to be updated, but that'll be some other time.

**Comment by demilich1** [comment]
I build a new release with webadict's newest fixes. Apologies for the delay; unfortunately I am very busy with my job right now, got next to no time for MetaStone at the moment. Here is hope that this will improve early next year though!

Feel free to try out 0.9.9a (which will be called just 0.9.9 for the users by the way - we will adopt the new versioning scheme with 1.0.0 as discussed).

**Comment by webadict** [comment]
Be sure to test the heck out of deathrattles!

**Comment by webadict** [comment]
All fixes from 0.9.8:
Rewrote death processing and sequencing.
Rewrote transformation processing.

Fixed Start of Turn Triggers.
Fixed Max Deck Size.
Fixed Choose One cards to act as Spells.
Fixed Prophet Velen to double healing and damage correctly.
Fixed Mistress of Pain to heal for damage dealt.
Fixed Mal'Ganis to do everything right.
Fixed Secret processing and targeting.
Fixed Floating Watcher to buff on own turn only.
Fixed Fel Cannon to target Mechs only.
Fixed Sword of Justice buffing when destroyed.
Fixed King's Elekk to draw the Joust card.
Fixed Mana Crystal generating to add full mana crystals when necessary.
Fixed Tracking.
Fixed mind control actions.
Fixed discarding and summoning from deck.
Fixed dead attacker and defender bugs.
Fixed Dark Iron Skulker to target full health minions.
Fixed Goblin Blast Mage to only activate when you own a minion.
Fixed auras not properly updating minion stats.
Fixed Lava Shock to no longer generate mana.
Fixed Competitive Spirit to activate on 1 or more minions.
Fixed Murloc Tidecaller to be 1/2 instead of 1/1.
Fixed Starfire to draw a card.
Fixed King's Defender to be a Warrior card.
Fixed Betrayal to activate minion abilities and not use Spell Damage.
Fixed Steamweedle Snipe to target correctly.
Fixed some minions to have the correct Race tag.
Fixed Drain Life to cost 3 mana instead of 2.
Updated Card Formatting.

Added Discover spells.
Added League of Explorers cards.

**Comment by mayuso** [comment]
Wow, thats a huge fix patch xD 

Didn´t realise, not even thought about how much you guys did in so little time. Amazing!

**Comment by webadict** [comment]
This is 0.9.9 and 0.9.9a combined, but yeah, there's still plenty to do. Aiming for bugfixes is pretty simple to do, but fixing some of the bigger, hidden issues (Battlecries, Deathrattles, Transformations, Discarding, etc.) are things I'd like to be fixed before it can be a truly completed simulator.

I'd like to be able to have a Custom Card Creator, so offloading some of the built-in things might need looking at (I know the Race and Class tags should be offloaded, so that additional or other races or classes can be added to the game, and I might do some rewriting of the card format.)

I'd like for the Sandbox mode to have a few less limitations and a bit more functionality to it. It works pretty well for what it is now, but I don't have access to the Graveyard, the Set Aside Zone, some of the hidden information on cards or entities that might be needed for testing. It's not overly oppressive, but it is something to fix and look into.

I'd like for the AI to be a bit better. I'd like a better way to test cards. I'd like to be able to add spells that people might use and increase the functionality of spells that are currently implemented. And triggers. And events. And a whole bunch of things. Like adventure mode battles or tavern brawl events! Not as a replacement for Hearthstone, but so that players actually have a stress-free place to test things out.

These are pretty big things, but I like this project, so I don't mind trying to do things I have no idea how to do. I'd like to send an open invitation to the custom hearthstone community, as well, so that they might pick up and start using Metastone as a testing ground for cards they create. It would help me (and hopefully Metastone itself) prepare for future expansions and adventures. But, I don't want to jump out and invite them to demilich's project. There's some cool custom cards I've seen made, but I don't think that's up to me to do, and it's not really an objective of the project itself, but that's something else I'd like to see done.

**Comment by demilich1** [comment]
I have decided to release the version flagged as 0.9.9a on my website. While there are still open bugs, I think the new version is stable enough and has many improvements compared to the previous version. Thanks again to everyone who helped testing, it was tremendously useful and we discovered many issues which could be fixed for the final version.
And of course, again special thanks to webadict who contributed the majority of this release.

I also thought about promoting MetaStone in the custom Hearthstone sub reddit, but I don't feel it's a useful tool for custom card creation just yet. At the very least we would need a documentation for the .json file format and a list of all spells, triggers, etc. Of course a GUI for creating custom cards would be even better (not everyone feels comfortable editing .json files with a text editor). Also, we need better error handling for custom cards. If you create an invalid .json file, the application just crashes without even telling you which card was wrong or what might be the issue.

I will close this issue for now; feel free to start create new issues for anything you would like to discuss.
