### ISSUE TITLE
New Races

### ISSUE THREAD

**Issue by blindfreak9** [demilich1/metastone#347]
Hi,
Was wondering if it's possible to add new custom races? Tried editing the Race.java file and adding it there but that doesn't work so I'm assuming there's more than just that. If so, how is it done? 

Thanks

**Comment by doombubbles** [comment]
You might have to be more specific with how it's not working, because that should be all you have to do.

**Comment by webadict** [comment]
Actually, it should be ass simple as updating the Race enum and recompiling. There isn't anything hardcoded for that one.

**Comment by percy896** [comment]
So it also doesn't work for me. This is a big roadblock that I've come across. Here's the issue and here's what we need help with:

When adding and editing cards, you simply go in and add a new .json file, reload Metastone, and poof, it's there and fully-functional (as long as you've coded it correctly). This does not happen with adding new races, probably because they are not in .json files. They are in .java files. I think blindfreak9 and I don't understand what you have to do differently to update the .java file, besides edit the text and add a new race to the list. We don't know how to "recompile" because we are less familiar with java. Can anyone please help us? Thank you!

**Comment by webadict** [comment]
The real issue is that it's not that simple to make it work. Heroes and Hero Classes are contained within an Enum. That would need to be removed to be able to do what you want. So the solution for now is to simply recompile it after changing, or wait until it becomes customizable, but I haven't had much time to add anything to the project.

**Comment by percy896** [comment]
...but how to you recompile it after changing? This is the question for us non-java users. Thank you.

**Comment by webadict** [comment]
I apologize, as I never really answered your question. However, you'll have to add code, which unfortunately isn't what you want to hear. In the future, this might become a feature, but that would be much further from now.

I will close your issue. You are free to reopen it, if you were waiting a year for an answer.
