### ISSUE TITLE
[Idea] Change to Poison Seeds' code for simplicity

### ISSUE THREAD

**Issue by Muhframos** [demilich1/metastone#350]
Wouldn't it be simpler to code Poison Seeds, for creating spells similar to it, like this: 

```
{
	"name": "Poison Seeds",
	"baseManaCost": 4,
	"type": "SPELL",
	"heroClass": "DRUID",
	"rarity": "COMMON",
	"description": "Destroy all minions and summon 2/2 treants to replace them",
	"targetSelection": "NONE",
	"spell": {
	"class": "MetaSpell",
	"spells": [
	{
		"class": "AddDeathrattleSpell",
		"target": "ALL_MINIONS",
		"spell": {
		"class": "SummonSpell",
		"card": "token_treant"
	}
	},
	{
		"class": "DestroySpell",
		"target": "ALL_MINIONS"
	}
	]
	},
	"collectible": true,
	"set": "NAXXRAMAS",
	"fileFormatVersion": 1
}
```

I have tested interactions like Baron Rivendare with this, and it doesnt trigger the Deathrattle twice.

**Comment by webadict** [comment]
Well, there are several reasons why this would fail.
1) Baron Rivendare. Yes, if he's simply on the field, it looks like it would fail. But, here's a simple scenario: He has Ancestral Spirit on him. Then he summons two Treants.
2) Death resolution order. This spell is missing a certain interaction step in between. All minions should be dead when deathrattles start going off, and then the Treants should be summoned. This prevents things like playing an Explosive Sheep, then playing Poison Seeds to clear everything except the one Treant your sheep would summon last.
3) Future interactions. You never know what interactions a card might have. It's best to follow that card as best as possible. The spell may look complicated, but it's because the card IS complicated.

Thanks, though.

**Comment by Muhframos** [comment]
Oh well, then, i guess this issue can be closed.

Thanks for the answer

**Comment by webadict** [comment]
No problem. This card has been a hassle to make simple l, and I know demilich and I have tried.
