### ISSUE TITLE
Point to Spellsource, the modern fork of metastone

### ISSUE THREAD

**Issue by doctorpangloss** [demilich1/metastone#387]
@demilich1 @webadict you think you guys can update the README here to navigate to

https://github.com/hiddenswitch/Spellsource-Server

which is the modern fork? I get so many surprised people and it would be easier to just link it directly.

-Ben

**Comment by webadict** [comment]
I can redirect the README as soon as Spellsource includes a Sandbox Mode. Without that, there is a fundamental gap in goals between the two projects, even if the overall outcome is very similar. I believe your project has a lot going for it, but its overall intent seems to be to replace Hearthstone, instead of complementing it.

I like Spellsource. It has a lot going for it. But, if MetaStone were to point towards it, it would be agreeing with the message your project espouses, and as (likely) the main contributor, I refuse to let the projects message differ from the intent @demilich1 had left it, especially with the amount of trust I was given.

I'll leave this issue open, so any new people browsing this project might see this, but I'm afraid that I cannot acquiesce until my concerns are met.
