### ISSUE TITLE
MetaStone needs to use Milestones more

### ISSUE THREAD

**Issue by mayuso** [demilich1/metastone#48]
This is more my own opinion than an issue, and will be closed as soon as possible.

I just think MetaStone should use Milestones more. You can add issues to the 0.9.10, 0.10.0 or even 1.0.0 Milestone, that way we (contributors) can see what Issues need to be fixed first, and we will be able to focus our attention and work to the most important issues.

What do you guys think?

**Comment by demilich1** [comment]
I agree. My suggestion for milestone semantics is as follows:

MetaStone uses version numbers of the form x.y.z

* z is the 'revision' part, it should basically be incremented whenever we release a new version with any changes
* y is the 'minor' version part: I suggest to increment it whenever we implement a new card expansion (does not matter if it is an adventure or a 'new card packs' expansion)
* x is the 'major' version: I am not really sure about this one. We could increment it whenever major features are added, however this is highly subjective. I would actually prefer to just increment it when 'minor' version would reach 10, i.e. every ten expansions

That being said, I think the next milestone should actually be 1.0.0. What do you think?

**Comment by mayuso** [comment]
I agree, except for a couple details, I would suggest this (it´s pretty much the same, with minor changes)

Z is 'minor patch' part. Just for bug fixes and minor implementations. (NOT every commit, of course)

(Y is nice, I like the idea to increment it with card expansions and adventures)

X is also nice, but no need to increment when Y gets 10. we can have "0.16.0" version, thats fine.
I have experience in API development, X usually increments when the API update is not backwards-compatible (Changes many functions and/or logic and, for example, programs using 0.9.1 API would not work with 1.0.0 API). We can´t apply that here, so i would say just increment when HUGE changes happen. (Examples: Massive UI Update, New card format...Etc).

[Semantic Versioning 2.0.0] (http://semver.org/)

**Comment by mayuso** [comment]
Forgot to answer your last question:

Yes, I think we could add current known bugs to 1.0.0 milestone and release it when we fix them.

Again, **don´t read my words as MUST do**.

**Comment by webadict** [comment]
Just my two cents, the way Mayuso said is how I've also seen it done for
the most part. It makes a lot of sense that way, too, since 1.0.0 sounds
like a finished project, but I don't see that being the case.

All of our current changes have been minor additions. Big changes to things
like battlecry and deathrattle rewrites would increment major version, as
well as card expansions, so those can be used for bigger picture deals.

So really, we should be on 0.10.0 after LoE. Since we didn't finish the
deathrattle update, we'd move it to 0.11.0.

Otherwise, the numbers might as well all be combined into a single number.
v99 is the same as v0.9.9 in this case.

**Comment by mayuso** [comment]
1.0.0 does sound like finished, sounds like stable public version.

I see your point on 0.10.0 instead of 1.0.0, but i still think it is a good time for 1.0.0, MetaStone has been on 0.y.z for a long time now and i feel it is pretty stable at this point (Except for minor bugs, which we can add to the 1.0.0 milestone).

I don´t like the idea of a single number, maybe it´s just that im already used to simple x.y.z, I just think it is simple enough for users to understand and deep enough to have a good version control (I mean the x.y.z system).
But this third point might be personal preference, I´m not sure if it is better or worse.

**Comment by demilich1** [comment]
It is tricky, on one hand 1.0.0 might sound too much like a finished product, on the other hand 0.10.0 sounds like pre-alpha-less-than-10-percent-is-done, which is also not true. I know that especially the Linux community uses 'low' version numbers like 0.10.0 for essentially finished libraries, but I don't really agree with that version scheme. So I basically see it like mayuso, 1.0.0 does not mean it is finished, but it is a public available, usable version of the application.

But I am open to other suggestions on this topic, does anyone else have an opinion about this?

**Comment by webadict** [comment]
I think I can agree that 1.0.0 should be released when all readily apparent bugs are worked out. But I know we still have to work through the deathrattle and battlecry sections before that happens, so maybe that is a good time to change release to 1.0.0. After that, does 1.10.0 sound like it's only 10% toward 2.0.0? It doesn't to me. I think just because it's solitary that 0.10.0 sounds like it's in its infancy.

**Comment by mayuso** [comment]
So, demilich1, webadict, what is the final decision? :)

**Comment by demilich1** [comment]
Let's keep the name of this release (with LoE) cards as 0.9.9. For the next release, we will fix the Deathrattle/Battlecry sequences and call it 1.0.0. After that, we will increment the middle number whenever Blizzard releases a new set of cards, the last number whenever we release a version which differs from the last one and the first one when major changes in MetaStone happen.

**Comment by mayuso** [comment]
Perfect :)
