### ISSUE TITLE
[Bug] Mal'Ganis 

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#50]
So the board is this:
http://i.pomf.pl/nniwvp.png

And as you can see, the Imps (gotten by Implosion) are 3/3, 5/5, and 7/7. I brought out Mal'Ganis via Voidcaller if that's any help, but what I think happened was when the imps were summoned they like gained 2/2 and then it went to 4/4 and then 6/6 for some reason. I don't know why but maybe there's something with Mal'Ganis and his coding.

**Comment by webadict** [comment]
... Well, crap. I honestly saw this as a possibility when I rewrote Mal'Ganis, but it seemed like it was working when I set it up... The problem is that the Aura reapplies to each Demon after it comes into play, so that each Demon buffs up the next Demon... Which isn't what I wanted.

I'll see what I can do about it.

**Comment by webadict** [comment]
Uh... I think I fixed it? I honestly don't know how, because Auras are weird, but I think it's working now.

**Comment by webadict** [comment]
Ha, I totally lied. Things are way worse than expected.

There's an underlying issue with this particular aura, really. It's trying to be like 12 things at once, and I honestly don't like how that's working (which is to say, not at all.) Currently, this Aura is trying to give itself to all other Demons, which isn't quite right to how it works. Basically, each Aura would stack upon itself, making things super bizarre.

So... I think I'll just make it way less bizarre.

**Comment by webadict** [comment]
Yeah, I guess simple is better. I fixed it.
