### ISSUE TITLE
Chose one spells do not work with malygos

### ISSUE THREAD

**Issue by beatcometz** [demilich1/metastone#53]
Living roots and wrath do not get additional spell power from malygos.
I've noticed that keeper of the grove works the same way (his 2 damage option is considered "DamageSpell" just like living roots and wrath).

**Comment by webadict** [comment]
Hmm, you're right. Alright, one more thing to add real quickly.

**Comment by webadict** [comment]
It doesn't have to do with the DamageSpell aspect, though. Rather, the Card Type is getting it confused. When the actions are rolled out for Choose One cards, I'm assuming the base card is denoted as the source card, which is what determines whether you are playing a Spell (which is affected by Spell Damage) and when you're playing a Minion with a Battlecry (which is not affected by Spell Damage), or, like this case, a Choose One card, which is totally separate from Spell cards.

It's a rather easy fix, though, so that's good.

**Comment by webadict** [comment]
Choose One spells now act like spells for the purpose of Secret processing and Spell Damage.
