### ISSUE TITLE
[Bug] Multiple Hobgoblins do not stack.

### ISSUE THREAD

**Issue by SirFatCat** [demilich1/metastone#55]
As in, if you have two Hobgoblins on the field (or more) and you play a 1-Attack minion, it will only gain a single buff rather than multiple buffs.

**Comment by webadict** [comment]
This is more than an issue with other types of effects as well. My guess is that each Triggered Effect activates in a Queue, with each Entity checking to see if their triggered ability activates on an Event. However, it really only checks the state after the Triggered effects before it, instead of adding all the Triggered effects that should happen, and using them in order.

It's basically the same issue as deathrattles. They went in order, not in phases.

**Comment by demilich1** [comment]
That COULD be true, however there may be another possibility. Maybe Hobgoblin just checks BASE_ATTACK attribute and does not care about any other applied attack buffs.

**Comment by webadict** [comment]
That'll work as a cover-up, but Hobgoblin should take your Attack at the moment of being played. This is because of Mistcaller interacting with Hobgoblin exactly like that, so that a Training Dummy that's been buffed in-hand to 1/3 WOULD gain from Hobgoblin's buff. Of course, the way it's setup now, Hobgoblin is bugged to buff 0 Attack minions anyhow, but that's a separate issue.

**Comment by webadict** [comment]
Rewrote Trigger processing to no longer check the Conditions while firing. Instead, the triggers are all checked on whether they can fire first, and then added to a list of triggered effects that activate in order.

**Comment by webadict** [comment]
This should be fixed in the next PR.
