### ISSUE TITLE
MetaStone on Linux

### ISSUE THREAD

**Issue by mayuso** [demilich1/metastone#66]
I have been using MetaStone for some Months already, but now I switched to ubuntu. 

I realised MetaStone installer is a .exe, so it is not really easy to make it work on any Linux system.
I think I could make every release work on Linux without needing any external application, but before working on this, any idea on how to upload this to github?

I think about creating different compiled versions for Windows and Linux. How can I upload this new version (when I make it work) to the repository?

**Comment by demilich1** [comment]
Well there is the raw .zip download which does not contain the JRE but only the application and required libraries. Since this is basically just a .jar file, it works fine on Linux. There is no installer for Linux though; however I think it would not 'fit' with the Linux culture to include the JRE with an installer, as everything is basically managed by the package managers and Linux users tend to favor applications which re-use existing modules already installed on the system such as the Java VM.

If you want to provide a better solution to the Linux users, the correct way would be to extend the build.gradle file to create an appropriate build.

**Comment by mayuso** [comment]
Why not an executable JRE? That´s the method I use at work all the time with Linux users who are not programmers or people interested in computers in general.

**Comment by demilich1** [comment]
Well if you visit http://www.demilich.net/metastone/download.html and download the file called 'Raw .jar file' you get an .zip archive which contains just that, an executable .jar. One could argue that .zip is not the most common archive format on Linux, so maybe we could change that to a tarball or something, but in essence this should be what you want, right? Maybe I should upload that on github also, as it is only available on my website for now.

**Comment by mayuso** [comment]
Oh, I did not even realise. Sorry.
Yes, I think a MetaStone.jar with each release (here on github) would be a great addition.

**Comment by mayuso** [comment]
Also, forgot to mention, yes, a simple runnable JAR is easier than a ZIP.
