### ISSUE TITLE
[Blessing of Wisdom] - mind controlling

### ISSUE THREAD

**Issue by demilich1** [demilich1/metastone#94]
Blessing of Wisdom does not work correctly when the targeted minion gets mind-controlled by the opponent. The same issue applies to Power Word: Glory

**Comment by demilich1** [comment]
I am working on this right now

**Comment by demilich1** [comment]
Okay, how does this actually work in real Hearthstone?

When I Blessing of Wisdom an enemy minion, he draws cards for me when attacking. Now what happens when I mind control this minion - will it still draw cards for myself or for my opponent?

**Comment by webadict** [comment]
In Hearthstone, whoever played the card will ALWAYS have the cards drawn
for them. This means through mind control, copying the minion, whatever.
The owner of the trigger should draw the cards. Currently, it works when
you play it on your own or an opponent's minion, but mind control switches
the card drawer, as does copying the opponent's minion. These two cards are
the only cases where this happens, as other cards don't really add triggers
to minions.

Okay, how does this actually work in real Hearthstone?

When I Blessing of Wisdom an enemy minion, he draws cards for me when
attacking. Now what happens when I mind control this minion - will it still
draw cards for myself or for my opponent?

—
Reply to this email directly or view it on GitHub
<https://github.com/demilich1/metastone/issues/94#issuecomment-193782842>.

**Comment by webadict** [comment]
From the Hearthstone wiki:

>Blessing of Wisdom creates an enchantment attached to the target minion, working the same way Power Word: Glory does.
>Even if the other player takes control of the minion Blessing of Wisdom was cast on, and whether you cast it on your minion or an opponent's minion, Blessing of Wisdom will always draw cards for the original caster.[1] (This is contrast to generated Deathrattles such as Ancestral Spirit or Explorer's Hat, which resolve their effects for the current controller of the minion.)
>If copied by Faceless Manipulator and Echoing Ooze, copies of the enchantment will still draw cards for the original caster, and not the player who copied it.

**Comment by demilich1** [comment]
Okay, but I just tested this and this is also how it works in MetaStone. I don't really understand WHY it works, because the owner should change when mind controlling. Need to dig a bit deeper into that

**Comment by webadict** [comment]
What? But... I tested it yesterday and it switched whom it drew cards for when I switched control of the minion.

**Comment by demilich1** [comment]
Yeah you are right. It works when you cast Blessing of Wisdom on an enemy minion (it will draw cards for you) and when you mind control it, it will still draw cards for you. But this is just because the owner and the player aligns in this case

**Comment by webadict** [comment]
So, is this a Mind Control error or a Trigger error?

**Comment by webadict** [comment]
Hey, while you're editting the mindControl function, can you rewrite this part:
`applyAttribute(minion, Attribute.SUMMONING_SICKNESS);`
to this
`if(!minion.hasAttribute(Attribute.CHARGE) {
applyAttribute(minion, Attribute.SUMMONING_SICKNESS);
}`

**Comment by demilich1** [comment]
That is not necessary, because the minion .canAttackThisTurn() method looks like this:

```
public boolean canAttackThisTurn() {
		if (hasAttribute(Attribute.CANNOT_ATTACK)) {
			return false;
		}
		if (hasAttribute(Attribute.FROZEN)) {
			return false;
		}
		if (hasAttribute(Attribute.SUMMONING_SICKNESS) && !hasAttribute(Attribute.CHARGE)) {
			return false;
		}
		return getAttack() > 0 && getAttributeValue(Attribute.NUMBER_OF_ATTACKS) > 0;
	}
```

So even if a minion has SUMMONING_SICKNESS, he will still be able to attack, as CHARGE basically overrides that

**Comment by webadict** [comment]
Weird... When I mind controlled a minion with Charge, it didn't work. I'll
check it out.
